name: GenVM get source
description: Checkout sources, optionally update submodules/third-party, and (optionally) set up Nix.
inputs:
  with_nix:
    description: if should setup nix
    required: false
    default: "false"
  load_submodules:
    description: if should update submodules
    required: false
    default: "true"
  third_party:
    description: third-party modules to install
    required: false
    default: --all
  github_token:
    description: GitHub token for nix setup
    required: false
runs:
  using: composite
  steps:
    - name: checkout submodules
      run: |
        cd "$GITHUB_WORKSPACE"
        git config --global user.email "worker@ci.ci"
        git config --global user.name "CI worker"
        if [ "${{ inputs.load_submodules }}" == "true" ]
        then
          git submodule update --init --recursive --depth 1
          if [ "${{ inputs.third_party }}" != "none" ]
          then
            source env.sh
            git third-party update ${{ inputs.third_party }}
          fi
        fi
      shell: bash -ex {0}
    - name: setup nix
      if: ${{ inputs.with_nix == 'true' }}
      uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes recursive-nix
        github_access_token: ${{ inputs.github_token }}
        install_url: https://releases.nixos.org/nix/nix-2.24.14/install
